// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF8VtP6RYsO_LMpBufnzvqvWOm-ozaDBo',
    appId: '1:978563852270:web:6fcaf87bb5641a4e2390ff',
    messagingSenderId: '978563852270',
    projectId: 'expense-8429a',
    authDomain: 'expense-8429a.firebaseapp.com',
    storageBucket: 'expense-8429a.firebasestorage.app',
    measurementId: 'G-ECTD30KSXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbOq-fxdpDHYKpNZjHOZrbd2yQZ6HgDSQ',
    appId: '1:978563852270:android:6a1ea2c650b709f42390ff',
    messagingSenderId: '978563852270',
    projectId: 'expense-8429a',
    storageBucket: 'expense-8429a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzZEQv--jb3o4NHf_ga-ZYnX06K4koqZo',
    appId: '1:978563852270:ios:3908ea72ec5929502390ff',
    messagingSenderId: '978563852270',
    projectId: 'expense-8429a',
    storageBucket: 'expense-8429a.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzZEQv--jb3o4NHf_ga-ZYnX06K4koqZo',
    appId: '1:978563852270:ios:3908ea72ec5929502390ff',
    messagingSenderId: '978563852270',
    projectId: 'expense-8429a',
    storageBucket: 'expense-8429a.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF8VtP6RYsO_LMpBufnzvqvWOm-ozaDBo',
    appId: '1:978563852270:web:ad1b2b51e11c99ee2390ff',
    messagingSenderId: '978563852270',
    projectId: 'expense-8429a',
    authDomain: 'expense-8429a.firebaseapp.com',
    storageBucket: 'expense-8429a.firebasestorage.app',
    measurementId: 'G-XXRB3E3Z47',
  );
}
